name: Weekly Credit Distribution

on:
  # cron format: minute hour day-of-month month day-of-week
  schedule:
    - cron: "0 0 * * 0"

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Call External API
        run: |

          curl -X POST 'https://crowdgraph.onrender.com/credit' \
            -H 'Content-Type: application/json' \
